services:
  app:
    build:
      context: .
    container_name: gorgia-agentspy
    command: uvicorn app.api:app --host 0.0.0.0 --port 8009 --reload --log-level debug
    volumes:
      - .:/app
    ports:
      - "8009:8009"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    tty: true
    stdin_open: true
